// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// project_pd_cpp
arma::mat project_pd_cpp(const arma::mat& M, const double eps);
RcppExport SEXP _GEMcluster_project_pd_cpp(SEXP MSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(project_pd_cpp(M, eps));
    return rcpp_result_gen;
END_RCPP
}
// factor_poet_map_cpp
List factor_poet_map_cpp(const arma::mat& A, const double lambda_u, const int M, const double eig_eps, const double pd_eps);
RcppExport SEXP _GEMcluster_factor_poet_map_cpp(SEXP ASEXP, SEXP lambda_uSEXP, SEXP MSEXP, SEXP eig_epsSEXP, SEXP pd_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_u(lambda_uSEXP);
    Rcpp::traits::input_parameter< const int >::type M(MSEXP);
    Rcpp::traits::input_parameter< const double >::type eig_eps(eig_epsSEXP);
    Rcpp::traits::input_parameter< const double >::type pd_eps(pd_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(factor_poet_map_cpp(A, lambda_u, M, eig_eps, pd_eps));
    return rcpp_result_gen;
END_RCPP
}
// poet_map_cpp
arma::mat poet_map_cpp(const arma::mat& A, const double lambda_u, const int m, const double pd_eps);
RcppExport SEXP _GEMcluster_poet_map_cpp(SEXP ASEXP, SEXP lambda_uSEXP, SEXP mSEXP, SEXP pd_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_u(lambda_uSEXP);
    Rcpp::traits::input_parameter< const int >::type m(mSEXP);
    Rcpp::traits::input_parameter< const double >::type pd_eps(pd_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(poet_map_cpp(A, lambda_u, m, pd_eps));
    return rcpp_result_gen;
END_RCPP
}
// l1_distance_matrix_cpp
NumericMatrix l1_distance_matrix_cpp(const NumericMatrix& X, const NumericMatrix& centers, const IntegerVector& use_dims);
RcppExport SEXP _GEMcluster_l1_distance_matrix_cpp(SEXP XSEXP, SEXP centersSEXP, SEXP use_dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type centers(centersSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type use_dims(use_dimsSEXP);
    rcpp_result_gen = Rcpp::wrap(l1_distance_matrix_cpp(X, centers, use_dims));
    return rcpp_result_gen;
END_RCPP
}
// calc_delta_cpp
arma::mat calc_delta_cpp(const arma::mat& X, const arma::mat& Mu, const arma::mat& Omega, const double eps);
RcppExport SEXP _GEMcluster_calc_delta_cpp(SEXP XSEXP, SEXP MuSEXP, SEXP OmegaSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< const double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_delta_cpp(X, Mu, Omega, eps));
    return rcpp_result_gen;
END_RCPP
}
// softmax_rows_cpp
NumericMatrix softmax_rows_cpp(const NumericMatrix& log_mat);
RcppExport SEXP _GEMcluster_softmax_rows_cpp(SEXP log_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type log_mat(log_matSEXP);
    rcpp_result_gen = Rcpp::wrap(softmax_rows_cpp(log_mat));
    return rcpp_result_gen;
END_RCPP
}
// row_logsumexp_cpp
NumericVector row_logsumexp_cpp(const NumericMatrix& log_mat);
RcppExport SEXP _GEMcluster_row_logsumexp_cpp(SEXP log_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type log_mat(log_matSEXP);
    rcpp_result_gen = Rcpp::wrap(row_logsumexp_cpp(log_mat));
    return rcpp_result_gen;
END_RCPP
}
// weighted_spatial_sign_scatter_cpp
NumericMatrix weighted_spatial_sign_scatter_cpp(const NumericMatrix& residuals, const NumericVector& weights, const double eps_r);
RcppExport SEXP _GEMcluster_weighted_spatial_sign_scatter_cpp(SEXP residualsSEXP, SEXP weightsSEXP, SEXP eps_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type residuals(residualsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const double >::type eps_r(eps_rSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_spatial_sign_scatter_cpp(residuals, weights, eps_r));
    return rcpp_result_gen;
END_RCPP
}
// quadform_rows_cpp
NumericVector quadform_rows_cpp(const NumericMatrix& residuals, const NumericMatrix& Omega);
RcppExport SEXP _GEMcluster_quadform_rows_cpp(SEXP residualsSEXP, SEXP OmegaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type residuals(residualsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Omega(OmegaSEXP);
    rcpp_result_gen = Rcpp::wrap(quadform_rows_cpp(residuals, Omega));
    return rcpp_result_gen;
END_RCPP
}
// weighted_crossprod_cpp
NumericMatrix weighted_crossprod_cpp(const NumericMatrix& residuals, const NumericVector& coeff);
RcppExport SEXP _GEMcluster_weighted_crossprod_cpp(SEXP residualsSEXP, SEXP coeffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type residuals(residualsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type coeff(coeffSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_crossprod_cpp(residuals, coeff));
    return rcpp_result_gen;
END_RCPP
}
// weighted_kde_eval_cpp
NumericVector weighted_kde_eval_cpp(const NumericVector& y_eval, const NumericVector& y_obs, const NumericVector& weights, const double bandwidth);
RcppExport SEXP _GEMcluster_weighted_kde_eval_cpp(SEXP y_evalSEXP, SEXP y_obsSEXP, SEXP weightsSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type y_eval(y_evalSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y_obs(y_obsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_kde_eval_cpp(y_eval, y_obs, weights, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// weighted_kde_eval_grid_cpp
NumericVector weighted_kde_eval_grid_cpp(const double y_start, const double y_step, const int grid_size, const NumericVector& y_obs, const NumericVector& weights, const double bandwidth);
RcppExport SEXP _GEMcluster_weighted_kde_eval_grid_cpp(SEXP y_startSEXP, SEXP y_stepSEXP, SEXP grid_sizeSEXP, SEXP y_obsSEXP, SEXP weightsSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type y_start(y_startSEXP);
    Rcpp::traits::input_parameter< const double >::type y_step(y_stepSEXP);
    Rcpp::traits::input_parameter< const int >::type grid_size(grid_sizeSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y_obs(y_obsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_kde_eval_grid_cpp(y_start, y_step, grid_size, y_obs, weights, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// col_medians_cpp
NumericVector col_medians_cpp(const NumericMatrix& X);
RcppExport SEXP _GEMcluster_col_medians_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(col_medians_cpp(X));
    return rcpp_result_gen;
END_RCPP
}
// cluster_centers_median_cpp
NumericMatrix cluster_centers_median_cpp(const NumericMatrix& X, const IntegerVector& cluster, const int K);
RcppExport SEXP _GEMcluster_cluster_centers_median_cpp(SEXP XSEXP, SEXP clusterSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type cluster(clusterSEXP);
    Rcpp::traits::input_parameter< const int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(cluster_centers_median_cpp(X, cluster, K));
    return rcpp_result_gen;
END_RCPP
}
// compute_between_ss_l1_cpp
double compute_between_ss_l1_cpp(const NumericMatrix& X, const IntegerVector& cluster, const int K);
RcppExport SEXP _GEMcluster_compute_between_ss_l1_cpp(SEXP XSEXP, SEXP clusterSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type cluster(clusterSEXP);
    Rcpp::traits::input_parameter< const int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_between_ss_l1_cpp(X, cluster, K));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GEMcluster_project_pd_cpp", (DL_FUNC) &_GEMcluster_project_pd_cpp, 2},
    {"_GEMcluster_factor_poet_map_cpp", (DL_FUNC) &_GEMcluster_factor_poet_map_cpp, 5},
    {"_GEMcluster_poet_map_cpp", (DL_FUNC) &_GEMcluster_poet_map_cpp, 4},
    {"_GEMcluster_l1_distance_matrix_cpp", (DL_FUNC) &_GEMcluster_l1_distance_matrix_cpp, 3},
    {"_GEMcluster_calc_delta_cpp", (DL_FUNC) &_GEMcluster_calc_delta_cpp, 4},
    {"_GEMcluster_softmax_rows_cpp", (DL_FUNC) &_GEMcluster_softmax_rows_cpp, 1},
    {"_GEMcluster_row_logsumexp_cpp", (DL_FUNC) &_GEMcluster_row_logsumexp_cpp, 1},
    {"_GEMcluster_weighted_spatial_sign_scatter_cpp", (DL_FUNC) &_GEMcluster_weighted_spatial_sign_scatter_cpp, 3},
    {"_GEMcluster_quadform_rows_cpp", (DL_FUNC) &_GEMcluster_quadform_rows_cpp, 2},
    {"_GEMcluster_weighted_crossprod_cpp", (DL_FUNC) &_GEMcluster_weighted_crossprod_cpp, 2},
    {"_GEMcluster_weighted_kde_eval_cpp", (DL_FUNC) &_GEMcluster_weighted_kde_eval_cpp, 4},
    {"_GEMcluster_weighted_kde_eval_grid_cpp", (DL_FUNC) &_GEMcluster_weighted_kde_eval_grid_cpp, 6},
    {"_GEMcluster_col_medians_cpp", (DL_FUNC) &_GEMcluster_col_medians_cpp, 1},
    {"_GEMcluster_cluster_centers_median_cpp", (DL_FUNC) &_GEMcluster_cluster_centers_median_cpp, 3},
    {"_GEMcluster_compute_between_ss_l1_cpp", (DL_FUNC) &_GEMcluster_compute_between_ss_l1_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_GEMcluster(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
