compute_gap_dispersion <- function(X, fit, soft = TRUE, eps = 1e-8) {
  Delta <- calc_delta(X, fit$Mu, fit$Omega, eps = eps)
  if (isTRUE(soft)) {
    return(sum(fit$Tau * Delta))
  }
  sum(Delta[cbind(seq_len(nrow(X)), fit$cluster)])
}

select_K_gap_1se <- function(K_grid, gap, sk) {
  m <- length(K_grid)
  if (m == 1L) {
    return(K_grid[1L])
  }
  for (i in seq_len(m - 1L)) {
    if (gap[i] >= gap[i + 1L] - sk[i + 1L]) {
      return(K_grid[i])
    }
  }
  K_grid[m]
}

.merge_gem_control <- function(control, defaults) {
  if (is.null(control)) {
    return(defaults)
  }
  defaults[names(control)] <- control
  defaults
}

#' Select K by the GAP statistic using GEM fits
#'
#' The reference distribution is generated by independently permuting each
#' feature column, matching the GAP code used in the simulation scripts.
#'
#' @param X n by p data matrix.
#' @param K_grid Candidate K values.
#' @param B Number of column-permutation reference samples.
#' @param control Named list passed to [gem_fit()].
#' @param soft_dispersion If TRUE, use posterior-weighted GEM dispersion.
#' @param seed Optional seed.
#' @param rule Either "1se" or "max"; controls `best_K`.
#' @param verbose Print progress.
#' @export
gem_select_k_gap <- function(X,
                             K_grid = 2:5,
                             B = 20L,
                             control = NULL,
                             soft_dispersion = TRUE,
                             seed = NULL,
                             rule = c("1se", "max"),
                             verbose = TRUE) {
  X <- as.matrix(X)
  K_grid <- sort(unique(as.integer(K_grid)))
  if (length(K_grid) < 1L || any(K_grid < 1L)) {
    stop("K_grid must contain positive integers.")
  }
  B <- as.integer(B)
  if (B < 1L) {
    stop("B must be at least 1.")
  }
  rule <- match.arg(rule)
  if (!is.null(seed)) {
    set.seed(seed)
  }

  defaults <- list(
    max_outer = 15L,
    tol = 2e-3,
    init_n_boot = 2L,
    init_nstart = 4L,
    init_max_iter = 40L,
    outer_nstart = 1L,
    verbose = FALSE
  )
  gem_control <- .merge_gem_control(control, defaults)
  nK <- length(K_grid)
  obs_fits <- vector("list", nK)
  obs_disp <- numeric(nK)
  obs_time <- numeric(nK)

  for (i in seq_along(K_grid)) {
    K_now <- K_grid[i]
    t_fit <- system.time({
      fit_now <- do.call(gem_fit, c(list(X = X, K = K_now), gem_control))
    })
    obs_fits[[i]] <- fit_now
    obs_disp[i] <- compute_gap_dispersion(X, fit_now, soft = soft_dispersion)
    obs_time[i] <- unname(t_fit["elapsed"])
    if (isTRUE(verbose)) {
      cat(sprintf("Observed K=%d: dispersion=%.4f, time=%.2fs\n", K_now, obs_disp[i], obs_time[i]))
    }
  }

  ref_log_disp <- matrix(NA_real_, nrow = nK, ncol = B)
  ref_time <- matrix(NA_real_, nrow = nK, ncol = B)
  for (b in seq_len(B)) {
    Xb <- permute_columns(X)
    if (isTRUE(verbose)) {
      cat(sprintf("Reference permutation %d/%d\n", b, B))
    }
    for (i in seq_along(K_grid)) {
      K_now <- K_grid[i]
      t_fit <- system.time({
        fit_b <- do.call(gem_fit, c(list(X = Xb, K = K_now), gem_control))
      })
      ref_disp_b <- compute_gap_dispersion(Xb, fit_b, soft = soft_dispersion)
      ref_log_disp[i, b] <- log(pmax(ref_disp_b, 1e-8))
      ref_time[i, b] <- unname(t_fit["elapsed"])
      if (isTRUE(verbose)) {
        cat(sprintf("  perm=%d, K=%d: dispersion=%.4f, time=%.2fs\n", b, K_now, ref_disp_b, ref_time[i, b]))
      }
    }
  }

  logW_obs <- log(pmax(obs_disp, 1e-8))
  gap <- rowMeans(ref_log_disp)
  gap <- gap - logW_obs
  sd_ref <- apply(ref_log_disp, 1L, stats::sd)
  sd_ref[!is.finite(sd_ref)] <- 0
  sk <- sqrt(1 + 1 / B) * sd_ref
  K_gap_max <- K_grid[which.max(gap)]
  K_gap_1se <- select_K_gap_1se(K_grid, gap, sk)
  best_K <- if (rule == "1se") K_gap_1se else K_gap_max

  summary_tab <- data.frame(
    K = K_grid,
    logW_obs = logW_obs,
    mean_logW_perm = rowMeans(ref_log_disp),
    sd_logW_perm = sd_ref,
    sk = sk,
    gap = gap,
    obs_dispersion = obs_disp,
    obs_time_sec = obs_time,
    ref_time_sec_mean = rowMeans(ref_time)
  )
  summary_tab$gap_to_next_minus_se <- c(gap[-nK] - (gap[-1L] - sk[-1L]), NA_real_)

  structure(list(
    summary = summary_tab,
    best_K = best_K,
    best_K_gap_max = K_gap_max,
    best_K_gap_1se = K_gap_1se,
    best_fit = obs_fits[[match(best_K, K_grid)]],
    best_fit_gap_1se = obs_fits[[match(K_gap_1se, K_grid)]],
    best_fit_gap_max = obs_fits[[match(K_gap_max, K_grid)]],
    obs_fits = setNames(obs_fits, paste0("K", K_grid)),
    ref_log_disp = ref_log_disp,
    control = gem_control,
    B = B,
    rule = rule
  ), class = "gem_gap")
}

#' Alias for GAP K selection
#' @export
gap_select_k <- gem_select_k_gap

#' @export
print.gem_gap <- function(x, ...) {
  cat("GEM GAP K selection\n")
  cat(sprintf("  best_K (%s rule): %d\n", x$rule, x$best_K))
  cat(sprintf("  best_K_gap_1se: %d\n", x$best_K_gap_1se))
  cat(sprintf("  best_K_gap_max: %d\n", x$best_K_gap_max))
  print(x$summary, row.names = FALSE)
  invisible(x)
}
