# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

project_pd_cpp <- function(M, eps = 1e-6) {
    .Call(`_GEMcluster_project_pd_cpp`, M, eps)
}

factor_poet_map_cpp <- function(A, lambda_u, M = 8L, eig_eps = 1e-8, pd_eps = 1e-6) {
    .Call(`_GEMcluster_factor_poet_map_cpp`, A, lambda_u, M, eig_eps, pd_eps)
}

poet_map_cpp <- function(A, lambda_u, m = 0L, pd_eps = 1e-6) {
    .Call(`_GEMcluster_poet_map_cpp`, A, lambda_u, m, pd_eps)
}

l1_distance_matrix_cpp <- function(X, centers, use_dims) {
    .Call(`_GEMcluster_l1_distance_matrix_cpp`, X, centers, use_dims)
}

calc_delta_cpp <- function(X, Mu, Omega, eps) {
    .Call(`_GEMcluster_calc_delta_cpp`, X, Mu, Omega, eps)
}

softmax_rows_cpp <- function(log_mat) {
    .Call(`_GEMcluster_softmax_rows_cpp`, log_mat)
}

row_logsumexp_cpp <- function(log_mat) {
    .Call(`_GEMcluster_row_logsumexp_cpp`, log_mat)
}

weighted_spatial_sign_scatter_cpp <- function(residuals, weights, eps_r) {
    .Call(`_GEMcluster_weighted_spatial_sign_scatter_cpp`, residuals, weights, eps_r)
}

quadform_rows_cpp <- function(residuals, Omega) {
    .Call(`_GEMcluster_quadform_rows_cpp`, residuals, Omega)
}

weighted_crossprod_cpp <- function(residuals, coeff) {
    .Call(`_GEMcluster_weighted_crossprod_cpp`, residuals, coeff)
}

weighted_kde_eval_cpp <- function(y_eval, y_obs, weights, bandwidth) {
    .Call(`_GEMcluster_weighted_kde_eval_cpp`, y_eval, y_obs, weights, bandwidth)
}

weighted_kde_eval_grid_cpp <- function(y_start, y_step, grid_size, y_obs, weights, bandwidth) {
    .Call(`_GEMcluster_weighted_kde_eval_grid_cpp`, y_start, y_step, grid_size, y_obs, weights, bandwidth)
}

col_medians_cpp <- function(X) {
    .Call(`_GEMcluster_col_medians_cpp`, X)
}

cluster_centers_median_cpp <- function(X, cluster, K) {
    .Call(`_GEMcluster_cluster_centers_median_cpp`, X, cluster, K)
}

compute_between_ss_l1_cpp <- function(X, cluster, K) {
    .Call(`_GEMcluster_compute_between_ss_l1_cpp`, X, cluster, K)
}

